<a href="https://colab.research.google.com/github/cnwokoye1/QR-Decomposition/blob/main/QR_Decomposition_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# generate matrix A with random int values
A = np.array(np.random.randint (0, 10, (3, 3)), dtype=np.float64)

##QR by Givens Rotations

In [5]:
def givensrotation(a, b):
  hypot = np.sqrt(a**2 + b**2)
  cos = a / hypot
  sin = -b / hypot
  return cos, sin

def qr_givens(A):
  m, n = A.shape
  R = A.copy()
  Q = np.identity(m)
  # loop over columns
  for i in range(0, n-1):
    # loop over rows
    for j in range(i+1, m):
      cos, sin = givensrotation(R[i, i], R[j, i])
      R[i], R[j] = (R[i] * cos) + (R[j] * (-sin)), (R[i] * sin) + (R[j] * cos)
      Q[:, i], Q[:, j] = (Q[:, i] * cos) + (Q[:, j] * (-sin)), (Q[:, i] * sin) + (Q[:, j] * cos)
  return Q, R

Q, R = qr_givens(A)
print("A: ")
print(A)
print("Q: ")
print(Q)
print("R: ")
print(np.round(R, 3))


A: 
[[2. 0. 9.]
 [9. 1. 7.]
 [0. 0. 9.]]
Q: 
[[ 0.21693046 -0.97618706  0.        ]
 [ 0.97618706  0.21693046  0.        ]
 [ 0.          0.          1.        ]]
R: 
[[ 9.22   0.976  8.786]
 [-0.     0.217 -7.267]
 [ 0.     0.     9.   ]]


##QR by Householder

In [8]:
def qr_householder(A):
  m, n = A.shape
  R = A.copy()
  Q = np.identity(m)
  # Loop over every column of matrix A except for the last
  for i in range(0, n - 1):
    alpha = np.linalg.norm(R[i:, i], 2)
    avec = np.zeros_like(R[i:, [i]])
    avec[0] = alpha
    u = R[i:, [i]] - avec
    v = u / np.linalg.norm(u, 2)
    Qn = np.identity(m - i) - (2 * np.dot(v, v.T))
    # The following line pads each submatrix w/ 1s along the diagonal and 0s
    # elsewhere so as to be able to still properly do matrix multiplication
    Qn = np.block([[np.eye(i), np.zeros((i, m - i))], [np.zeros((m - i, i)), Qn]])
    R = np.dot(Qn, R)
    Q = np.dot(Q, Qn.T)
  return Q, R

Q, R = qr_householder(A)
print("A: ")
print(A)
print("Q:")
print(Q)
print("R:")
print(np.round(R, 3))

A: 
[[2. 0. 9.]
 [9. 1. 7.]
 [0. 0. 9.]]
Q:
[[ 0.21693046 -0.97618706  0.        ]
 [ 0.97618706  0.21693046  0.        ]
 [ 0.          0.          1.        ]]
R:
[[ 9.22   0.976  8.786]
 [ 0.     0.217 -7.267]
 [ 0.     0.     9.   ]]
