<a href="https://colab.research.google.com/github/cnwokoye1/QR-Decomposition/blob/main/QR_Decomposition_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

# generate matrix A with random int values
A = np.array(np.random.randint (0, 10, (3, 3)), dtype=np.float64)

## QR by Gram-Schmidt

In [11]:
def gram_schmidt(A):
    m, n  = A.shape
    Q = np.zeros((m, n))
    Q[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0], 2)
    for i in range(1, n):
        Q[:, i] = A[:, i]
        for j in range(0, i):
            inner = np.dot(Q[:, j].T, Q[:, i])
            Q[:, i] = Q[:, i] - np.dot(inner, Q[:, j])
        Q[:, i] = Q[:, i] / np.linalg.norm(Q[:, i], 2)
    return Q

def qr_gs(A):
    m, n = A.shape
    Q = gram_schmidt(A)
    R = np.zeros((m, n))
    for i in range(0, n):
        R[i, i] = np.dot(Q[:, i], A[:, i])
        for j in range(0, i):
            R[j, i] = np.dot(Q[:, j], A[:, i])
    return Q, R

Q, R = qr_gs(A)
print("A: ")
print(A)
print("Q: ")
print(Q)
print("R: ")
print(np.round(R, 3))


A: 
[[4. 4. 9.]
 [4. 3. 2.]
 [3. 4. 6.]]
Q: 
[[ 0.62469505  0.06941056  0.77777778]
 [ 0.62469505 -0.64204769 -0.44444444]
 [ 0.46852129  0.76351617 -0.44444444]]
R: 
[[6.403 6.247 9.683]
 [0.    1.406 3.922]
 [0.    0.    3.444]]


##QR by Givens Rotations

In [12]:
def givensrotation(a, b):
  hypot = np.sqrt(a**2 + b**2)
  cos = a / hypot
  sin = -b / hypot
  return cos, sin

def qr_givens(A):
  m, n = A.shape
  R = A.copy()
  Q = np.identity(m)
  # loop over columns
  for i in range(0, n-1):
    # loop over rows
    for j in range(i+1, m):
      cos, sin = givensrotation(R[i, i], R[j, i])
      R[i], R[j] = (R[i] * cos) + (R[j] * (-sin)), (R[i] * sin) + (R[j] * cos)
      Q[:, i], Q[:, j] = (Q[:, i] * cos) + (Q[:, j] * (-sin)), (Q[:, i] * sin) + (Q[:, j] * cos)
  return Q, R

Q, R = qr_givens(A)
print("A: ")
print(A)
print("Q: ")
print(Q)
print("R: ")
print(np.round(R, 3))


A: 
[[4. 4. 9.]
 [4. 3. 2.]
 [3. 4. 6.]]
Q: 
[[ 0.62469505  0.06941056  0.77777778]
 [ 0.62469505 -0.64204769 -0.44444444]
 [ 0.46852129  0.76351617 -0.44444444]]
R: 
[[ 6.403  6.247  9.683]
 [ 0.     1.406  3.922]
 [-0.     0.     3.444]]


##QR by Householder

In [13]:
def qr_householder(A):
  m, n = A.shape
  R = A.copy()
  Q = np.identity(m)
  # Loop over every column of matrix A except for the last
  for i in range(0, n - 1):
    alpha = np.linalg.norm(R[i:, i], 2)
    avec = np.zeros_like(R[i:, [i]])
    avec[0] = alpha
    u = R[i:, [i]] - avec
    v = u / np.linalg.norm(u, 2)
    Qn = np.identity(m - i) - (2 * np.dot(v, v.T))
    # The following line pads each submatrix w/ 1s along the diagonal and 0s
    # elsewhere so as to be able to still properly do matrix multiplication
    Qn = np.block([[np.eye(i), np.zeros((i, m - i))], [np.zeros((m - i, i)), Qn]])
    R = np.dot(Qn, R)
    Q = np.dot(Q, Qn.T)
  return Q, R

Q, R = qr_householder(A)
print("A: ")
print(A)
print("Q:")
print(Q)
print("R:")
print(np.round(R, 3))

A: 
[[4. 4. 9.]
 [4. 3. 2.]
 [3. 4. 6.]]
Q:
[[ 0.62469505  0.06941056  0.77777778]
 [ 0.62469505 -0.64204769 -0.44444444]
 [ 0.46852129  0.76351617 -0.44444444]]
R:
[[ 6.403  6.247  9.683]
 [ 0.     1.406  3.922]
 [-0.    -0.     3.444]]
